name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: make

    - name: Run demo and produce an output scene
      run: ./demo output.ppm

    - name: Upload rendered image
      uses: actions/upload-artifact@v3
      with:
        name: rendered-image
        path: output.ppm
